// export const employeeFile = [
//   {
//       "EmployeeId": null,
//       "EmployeeCode": "NV01",
//       "FullName": "Nguyễn Văn Mạnh",
//       "Gender": 0,
//       "GenderString": "Nam",
//       "Nationality": "Việt Nam",
//       "Ethnicity": "Kinh",
//       "ContractNumber": null,
//       "ContractType": null,
//       "DateOfBirth": null,
//       "DateOfBirthString": null,
//       "DepartmentId": "45ac3d26-18f2-18a9-3031-644313fbb055",
//       "DepartmentName": "Phòng Nghiên cứu",
//       "PositionId": "3e39129b-279f-623f-88ea-778aee59fea3",
//       "PositionName": "Giám đốc",
//       "IdentityNumber": "123456789",
//       "IdentityDate": "2019-09-05T00:00:00",
//       "IdentityDateString": "05/09/2019",
//       "IdentityPlace": "CA TP Hà Nội",
//       "Address": "phường Thống Nhất, TP Hải Dương, tỉnh Hải Dương",
//       "MobilePhoneNumber": "978256145",
//       "LandlinePhoneNumber": null,
//       "Email": "nvan@gmail.com",
//       "Salary": 45000000,
//       "BankAccountNumber": null,
//       "BankName": null,
//       "Branch": null,
//       "JoinDate": null,
//       "IsCustomer": null,
//       "IsSupplier": null,
//       "CreatedDate": null,
//       "CreatedBy": null,
//       "ModifiedDate": null,
//       "ModifiedBy": null,
//       "ImportInvalidErrors": [],
//       "IsImported": null,
//       "CanImported": true
//   },
//   {
//       "EmployeeId": null,
//       "EmployeeCode": "NV02",
//       "FullName": "Mai Tiến Thành",
//       "Gender": 1,
//       "GenderString": "Nữ",
//       "Nationality": "Việt Nam",
//       "Ethnicity": "Kinh",
//       "ContractNumber": null,
//       "ContractType": null,
//       "DateOfBirth": "1990-01-01T00:00:00",
//       "DateOfBirthString": "01/01/1990",
//       "DepartmentId": "7c4f14d8-66fb-14ae-198f-6354f958f4c0",
//       "DepartmentName": "Phòng Đào tạo",
//       "PositionId": "6528b15d-6674-724f-79a4-4b24de418577",
//       "PositionName": "Nhân viên",
//       "IdentityNumber": null,
//       "IdentityDate": null,
//       "IdentityDateString": null,
//       "IdentityPlace": null,
//       "Address": null,
//       "MobilePhoneNumber": null,
//       "LandlinePhoneNumber": null,
//       "Email": null,
//       "Salary": 6200000,
//       "BankAccountNumber": null,
//       "BankName": null,
//       "Branch": null,
//       "JoinDate": null,
//       "IsCustomer": null,
//       "IsSupplier": null,
//       "CreatedDate": null,
//       "CreatedBy": null,
//       "ModifiedDate": null,
//       "ModifiedBy": null,
//       "ImportInvalidErrors": [],
//       "IsImported": null,
//       "CanImported": true
//   },
//   {
//       "EmployeeId": null,
//       "EmployeeCode": "NV03",
//       "FullName": "Nguyễn Thành Trung",
//       "Gender": 0,
//       "GenderString": "Nam",
//       "Nationality": "Việt Nam",
//       "Ethnicity": "Kinh",
//       "ContractNumber": null,
//       "ContractType": null,
//       "DateOfBirth": null,
//       "DateOfBirthString": null,
//       "DepartmentId": "45ac3d26-18f2-18a9-3031-644313fbb055",
//       "DepartmentName": "Phòng Nghiên cứu",
//       "PositionId": "6528b15d-6674-724f-79a4-4b24de418577",
//       "PositionName": "Nhân viên",
//       "IdentityNumber": "1243456789",
//       "IdentityDate": "2019-09-05T00:00:00",
//       "IdentityDateString": "05/09/2019",
//       "IdentityPlace": "CA TP Hà Nội",
//       "Address": "phường Thống Nhất, TP Hải Dương, tỉnh Hải Dương",
//       "MobilePhoneNumber": "978256145",
//       "LandlinePhoneNumber": null,
//       "Email": "nvan@gmail.com",
//       "Salary": 350000,
//       "BankAccountNumber": null,
//       "BankName": null,
//       "Branch": null,
//       "JoinDate": null,
//       "IsCustomer": null,
//       "IsSupplier": null,
//       "CreatedDate": null,
//       "CreatedBy": null,
//       "ModifiedDate": null,
//       "ModifiedBy": null,
//       "ImportInvalidErrors": [
//           "Mã nhân viên đã trùng với nhân viên khác trong tệp"
//       ],
//       "IsImported": null,
//       "CanImported": false
//   },
//   {
//       "EmployeeId": null,
//       "EmployeeCode": "NV04",
//       "FullName": "Nguyễn Thanh Bình",
//       "Gender": 0,
//       "GenderString": "Nam",
//       "Nationality": "Việt Nam",
//       "Ethnicity": "Kinh",
//       "ContractNumber": null,
//       "ContractType": null,
//       "DateOfBirth": null,
//       "DateOfBirthString": null,
//       "DepartmentId": "45ac3d26-18f2-18a9-3031-644313fbb055",
//       "DepartmentName": "Phòng Nghiên cứu",
//       "PositionId": "6528b15d-6674-724f-79a4-4b24de418577",
//       "PositionName": "Nhân viên",
//       "IdentityNumber": "123556789",
//       "IdentityDate": "2019-09-05T00:00:00",
//       "IdentityDateString": "05/09/2019",
//       "IdentityPlace": "CA TP Hà Nội",
//       "Address": "phường Thống Nhất, TP Hải Dương, tỉnh Hải Dương",
//       "MobilePhoneNumber": "978256145",
//       "LandlinePhoneNumber": null,
//       "Email": "nvan@gmail.com",
//       "Salary": null,
//       "BankAccountNumber": null,
//       "BankName": null,
//       "Branch": null,
//       "JoinDate": null,
//       "IsCustomer": null,
//       "IsSupplier": null,
//       "CreatedDate": null,
//       "CreatedBy": null,
//       "ModifiedDate": null,
//       "ModifiedBy": null,
//       "ImportInvalidErrors": [],
//       "IsImported": null,
//       "CanImported": true
//   },
//   {
//       "EmployeeId": null,
//       "EmployeeCode": "NV05",
//       "FullName": "Nguyễn Văn Minh",
//       "Gender": 0,
//       "GenderString": "Nam",
//       "Nationality": "Việt Nam",
//       "Ethnicity": "Kinh",
//       "ContractNumber": null,
//       "ContractType": null,
//       "DateOfBirth": null,
//       "DateOfBirthString": null,
//       "DepartmentId": "45ac3d26-18f2-18a9-3031-644313fbb055",
//       "DepartmentName": "Phòng Nghiên cứu",
//       "PositionId": "6528b15d-6674-724f-79a4-4b24de418577",
//       "PositionName": "Nhân viên",
//       "IdentityNumber": "123656789",
//       "IdentityDate": "2019-09-05T00:00:00",
//       "IdentityDateString": "05/09/2019",
//       "IdentityPlace": "CA TP Hà Nội",
//       "Address": "phường Thống Nhất, TP Hải Dương, tỉnh Hải Dương",
//       "MobilePhoneNumber": "978256145",
//       "LandlinePhoneNumber": null,
//       "Email": "nvan@gmail.com",
//       "Salary": 2500000,
//       "BankAccountNumber": null,
//       "BankName": null,
//       "Branch": null,
//       "JoinDate": null,
//       "IsCustomer": null,
//       "IsSupplier": null,
//       "CreatedDate": null,
//       "CreatedBy": null,
//       "ModifiedDate": null,
//       "ModifiedBy": null,
//       "ImportInvalidErrors": [],
//       "IsImported": null,
//       "CanImported": true
//   },
//   {
//       "EmployeeId": null,
//       "EmployeeCode": "NV03",
//       "FullName": "Nguyễn Văn Toàn",
//       "Gender": 0,
//       "GenderString": "Nam",
//       "Nationality": "Việt Nam",
//       "Ethnicity": "Kinh",
//       "ContractNumber": null,
//       "ContractType": null,
//       "DateOfBirth": null,
//       "DateOfBirthString": null,
//       "DepartmentId": null,
//       "DepartmentName": "Phòng tuyển dụng",
//       "PositionId": "6528b15d-6674-724f-79a4-4b24de418577",
//       "PositionName": "Nhân viên",
//       "IdentityNumber": "1243456789",
//       "IdentityDate": "2019-09-05T00:00:00",
//       "IdentityDateString": "05/09/2019",
//       "IdentityPlace": "CA TP Hà Nội",
//       "Address": "phường Thống Nhất, TP Hải Dương, tỉnh Hải Dương",
//       "MobilePhoneNumber": "978256145",
//       "LandlinePhoneNumber": null,
//       "Email": "nvan@gmail.com",
//       "Salary": 350000,
//       "BankAccountNumber": null,
//       "BankName": null,
//       "Branch": null,
//       "JoinDate": null,
//       "IsCustomer": null,
//       "IsSupplier": null,
//       "CreatedDate": null,
//       "CreatedBy": null,
//       "ModifiedDate": null,
//       "ModifiedBy": null,
//       "ImportInvalidErrors": [
//           "Đơn vị không có trong hệ thống",
//           "Mã nhân viên đã trùng với nhân viên khác trong tệp"
//       ],
//       "IsImported": null,
//       "CanImported": false
//   }
// ];

export const employeeFile = [
  {
      "EmployeeCode": "NV01",
      "FullName": "Nguyễn Văn Mạnh",
      "Gender": 0,
      "GenderString": "Nam",
      "Nationality": "Việt Nam",
      "Ethnicity": "Kinh",
      "ContractNumber": null,
      "ContractType": null,
      "DateOfBirth": "1990-09-15T00:00:00",
      "DateOfBirthString": "15/09/1990",
      "DepartmentId": "45ac3d26-18f2-18a9-3031-644313fbb055",
      "DepartmentName": "Phòng Nghiên cứu",
      "PositionId": "3e39129b-279f-623f-88ea-778aee59fea3",
      "PositionName": "Giám đốc",
      "IdentityNumber": "123456789",
      "IdentityDate": "2019-09-05T00:00:00",
      "IdentityDateString": "05/09/2019",
      "IdentityPlace": "CA TP Hà Nội",
      "Address": "phường Thống Nhất, TP Hải Dương, tỉnh Hải Dương",
      "MobilePhoneNumber": "978256145",
      "LandlinePhoneNumber": null,
      "Email": "nvan@gmail.com",
      "Salary": 45000000,
      "BankAccountNumber": null,
      "BankName": null,
      "Branch": null,
      "JoinDate": null,
      "IsCustomer": null,
      "IsSupplier": null,
      "CreatedDate": null,
      "CreatedBy": null,
      "ModifiedDate": null,
      "ModifiedBy": null,
      "ImportInvalidErrors": [],
      "IsImported": null,
      "CanImported": true
  },
  {
      "EmployeeCode": "NV02",
      "FullName": "Mai Tiến Thành",
      "Gender": 1,
      "GenderString": "Nữ",
      "Nationality": "Việt Nam",
      "Ethnicity": "Kinh",
      "ContractNumber": null,
      "ContractType": null,
      "DateOfBirth": null,
      "DateOfBirthString": null,
      "DepartmentId": "7c4f14d8-66fb-14ae-198f-6354f958f4c0",
      "DepartmentName": "Phòng Đào tạo",
      "PositionId": "6528b15d-6674-724f-79a4-4b24de418577",
      "PositionName": "Nhân viên",
      "IdentityNumber": null,
      "IdentityDate": null,
      "IdentityDateString": null,
      "IdentityPlace": null,
      "Address": null,
      "MobilePhoneNumber": null,
      "LandlinePhoneNumber": null,
      "Email": null,
      "Salary": 6200000,
      "BankAccountNumber": null,
      "BankName": null,
      "Branch": null,
      "JoinDate": null,
      "IsCustomer": null,
      "IsSupplier": null,
      "CreatedDate": null,
      "CreatedBy": null,
      "ModifiedDate": null,
      "ModifiedBy": null,
      "ImportInvalidErrors": [],
      "IsImported": null,
      "CanImported": true
  },
  {
      "EmployeeCode": "NV03",
      "FullName": "Nguyễn Thành Trung",
      "Gender": 0,
      "GenderString": "Nam",
      "Nationality": "Việt Nam",
      "Ethnicity": "Kinh",
      "ContractNumber": null,
      "ContractType": null,
      "DateOfBirth": "1999-02-15T00:00:00",
      "DateOfBirthString": "15/02/1999",
      "DepartmentId": "45ac3d26-18f2-18a9-3031-644313fbb055",
      "DepartmentName": "Phòng Nghiên cứu",
      "PositionId": "6528b15d-6674-724f-79a4-4b24de418577",
      "PositionName": "Nhân viên",
      "IdentityNumber": "1243456789",
      "IdentityDate": "2019-09-05T00:00:00",
      "IdentityDateString": "05/09/2019",
      "IdentityPlace": "CA TP Hà Nội",
      "Address": "phường Thống Nhất, TP Hải Dương, tỉnh Hải Dương",
      "MobilePhoneNumber": "978256145",
      "LandlinePhoneNumber": null,
      "Email": "nvan@gmail.com",
      "Salary": 350000,
      "BankAccountNumber": null,
      "BankName": null,
      "Branch": null,
      "JoinDate": null,
      "IsCustomer": null,
      "IsSupplier": null,
      "CreatedDate": null,
      "CreatedBy": null,
      "ModifiedDate": null,
      "ModifiedBy": null,
      "ImportInvalidErrors": [
          "Mã nhân viên đã trùng với nhân viên khác trong tệp"
      ],
      "IsImported": null,
      "CanImported": false
  },
  {
      "EmployeeCode": "NV04",
      "FullName": "Nguyễn Thanh Bình",
      "Gender": 0,
      "GenderString": "Nam",
      "Nationality": "Việt Nam",
      "Ethnicity": "Kinh",
      "ContractNumber": null,
      "ContractType": null,
      "DateOfBirth": "1999-02-15T00:00:00",
      "DateOfBirthString": "15/02/1999",
      "DepartmentId": "45ac3d26-18f2-18a9-3031-644313fbb055",
      "DepartmentName": "Phòng Nghiên cứu",
      "PositionId": "6528b15d-6674-724f-79a4-4b24de418577",
      "PositionName": "Nhân viên",
      "IdentityNumber": "123556789",
      "IdentityDate": "2019-09-05T00:00:00",
      "IdentityDateString": "05/09/2019",
      "IdentityPlace": "CA TP Hà Nội",
      "Address": "phường Thống Nhất, TP Hải Dương, tỉnh Hải Dương",
      "MobilePhoneNumber": "978256145",
      "LandlinePhoneNumber": null,
      "Email": "nvan@gmail.com",
      "Salary": null,
      "BankAccountNumber": null,
      "BankName": null,
      "Branch": null,
      "JoinDate": null,
      "IsCustomer": null,
      "IsSupplier": null,
      "CreatedDate": null,
      "CreatedBy": null,
      "ModifiedDate": null,
      "ModifiedBy": null,
      "ImportInvalidErrors": [],
      "IsImported": null,
      "CanImported": true
  },
  {
      "EmployeeCode": "NV05",
      "FullName": "Nguyễn Văn Minh",
      "Gender": 0,
      "GenderString": "Nam",
      "Nationality": "Việt Nam",
      "Ethnicity": "Kinh",
      "ContractNumber": null,
      "ContractType": null,
      "DateOfBirth": "1990-01-01T00:00:00",
      "DateOfBirthString": "01/01/1990",
      "DepartmentId": "45ac3d26-18f2-18a9-3031-644313fbb055",
      "DepartmentName": "Phòng Nghiên cứu",
      "PositionId": "6528b15d-6674-724f-79a4-4b24de418577",
      "PositionName": "Nhân viên",
      "IdentityNumber": "123656789",
      "IdentityDate": "2019-09-05T00:00:00",
      "IdentityDateString": "05/09/2019",
      "IdentityPlace": "CA TP Hà Nội",
      "Address": "phường Thống Nhất, TP Hải Dương, tỉnh Hải Dương",
      "MobilePhoneNumber": "978256145",
      "LandlinePhoneNumber": null,
      "Email": "nvan@gmail.com",
      "Salary": 2500000,
      "BankAccountNumber": null,
      "BankName": null,
      "Branch": null,
      "JoinDate": null,
      "IsCustomer": null,
      "IsSupplier": null,
      "CreatedDate": null,
      "CreatedBy": null,
      "ModifiedDate": null,
      "ModifiedBy": null,
      "ImportInvalidErrors": [],
      "IsImported": null,
      "CanImported": true
  },
  {
      "EmployeeCode": "NV03",
      "FullName": "Nguyễn Văn Toàn",
      "Gender": 0,
      "GenderString": "Nam",
      "Nationality": "Việt Nam",
      "Ethnicity": "Kinh",
      "ContractNumber": null,
      "ContractType": null,
      "DateOfBirth": "1999-02-15T00:00:00",
      "DateOfBirthString": "15/02/1999",
      "DepartmentId": null,
      "DepartmentName": "Phòng tuyển dụng",
      "PositionId": "6528b15d-6674-724f-79a4-4b24de418577",
      "PositionName": "Nhân viên",
      "IdentityNumber": "1243456789",
      "IdentityDate": "2019-09-05T00:00:00",
      "IdentityDateString": "05/09/2019",
      "IdentityPlace": "CA TP Hà Nội",
      "Address": "phường Thống Nhất, TP Hải Dương, tỉnh Hải Dương",
      "MobilePhoneNumber": "978256145",
      "LandlinePhoneNumber": null,
      "Email": "nvan@gmail.com",
      "Salary": 350000,
      "BankAccountNumber": null,
      "BankName": null,
      "Branch": null,
      "JoinDate": null,
      "IsCustomer": null,
      "IsSupplier": null,
      "CreatedDate": null,
      "CreatedBy": null,
      "ModifiedDate": null,
      "ModifiedBy": null,
      "ImportInvalidErrors": [
          "Đơn vị không có trong hệ thống",
          "Mã nhân viên đã trùng với nhân viên khác trong tệp"
      ],
      "IsImported": null,
      "CanImported": false
  }
];