//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MISA.CUKCUK.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MISAEmployeeImportResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MISAEmployeeImportResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MISA.CUKCUK.Core.Resources.MISAEmployeeImportResource", typeof(MISAEmployeeImportResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đơn vị không có trong hệ thống..
        /// </summary>
        public static string DepartmentNotExist {
            get {
                return ResourceManager.GetString("DepartmentNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã nhân viên đã trùng trong hệ thống..
        /// </summary>
        public static string EmployeeCodeDuplicateInDB {
            get {
                return ResourceManager.GetString("EmployeeCodeDuplicateInDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã nhân viên đã trùng với nhân viên khác trong tệp..
        /// </summary>
        public static string EmployeeCodeDuplicateInFile {
            get {
                return ResourceManager.GetString("EmployeeCodeDuplicateInFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã nhân viên không được để trống..
        /// </summary>
        public static string EmployeeCodeIsRequired {
            get {
                return ResourceManager.GetString("EmployeeCodeIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File nhập khẩu phải là file Excel..
        /// </summary>
        public static string FileIsNotExcel {
            get {
                return ResourceManager.GetString("FileIsNotExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File không được để trống..
        /// </summary>
        public static string FileIsRequired {
            get {
                return ResourceManager.GetString("FileIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chức vụ không có trong hệ thống..
        /// </summary>
        public static string PositionNotExist {
            get {
                return ResourceManager.GetString("PositionNotExist", resourceCulture);
            }
        }
    }
}
