//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MISA.CUKCUK.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MISAResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MISAResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MISA.CUKCUK.Core.Resources.MISAResource", typeof(MISAResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string BaseError {
            get {
                return ResourceManager.GetString("BaseError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã khách hàng đã tồn tại.
        /// </summary>
        public static string CustomerCodeIsDuplicated {
            get {
                return ResourceManager.GetString("CustomerCodeIsDuplicated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã khách hàng không được để trống.
        /// </summary>
        public static string CustomerCodeRequired {
            get {
                return ResourceManager.GetString("CustomerCodeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khách hàng chưa tồn tại trong hệ thống.
        /// </summary>
        public static string CustomerDoesNotExist {
            get {
                return ResourceManager.GetString("CustomerDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhóm khách hàng không tồn tại trong hệ thống.
        /// </summary>
        public static string CustomerGroupDoesNotExist {
            get {
                return ResourceManager.GetString("CustomerGroupDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to khách hàng đã tồn tại.
        /// </summary>
        public static string CustomerGroupNameIsDuplicated {
            get {
                return ResourceManager.GetString("CustomerGroupNameIsDuplicated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên nhóm khách hàng không được để trống.
        /// </summary>
        public static string CustomerGroupNameRequired {
            get {
                return ResourceManager.GetString("CustomerGroupNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày sinh không hợp lệ.
        /// </summary>
        public static string DateOfBirthInvalid {
            get {
                return ResourceManager.GetString("DateOfBirthInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số tiền nợ không được âm, và chỉ chứa số.
        /// </summary>
        public static string DebitAmoutInvalid {
            get {
                return ResourceManager.GetString("DebitAmoutInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã đơn vị đã tồn tại.
        /// </summary>
        public static string DepartmentCodeIsDuplicated {
            get {
                return ResourceManager.GetString("DepartmentCodeIsDuplicated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đơn vị chưa tồn tại trong hệ thống.
        /// </summary>
        public static string DepartmentDoesNotExist {
            get {
                return ResourceManager.GetString("DepartmentDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email không đúng định dạng.
        /// </summary>
        public static string EmailInvalid {
            get {
                return ResourceManager.GetString("EmailInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email không được để trống.
        /// </summary>
        public static string EmailRequired {
            get {
                return ResourceManager.GetString("EmailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã nhân viên đã tồn tại.
        /// </summary>
        public static string EmployeeCodeIsDuplicated {
            get {
                return ResourceManager.GetString("EmployeeCodeIsDuplicated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhân viên chưa tồn tại trong hệ thống.
        /// </summary>
        public static string EmployeeDoesNotExist {
            get {
                return ResourceManager.GetString("EmployeeDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh sách nhân viên.
        /// </summary>
        public static string EmployeeFileHeader {
            get {
                return ResourceManager.GetString("EmployeeFileHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh_sach_nhan_vien.
        /// </summary>
        public static string EmployeeFileName {
            get {
                return ResourceManager.GetString("EmployeeFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh sách nhân viên.
        /// </summary>
        public static string EmployeeWorkSheetName {
            get {
                return ResourceManager.GetString("EmployeeWorkSheetName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã xảy ra lỗi trong quá trình xuất file..
        /// </summary>
        public static string ExportFileFail {
            get {
                return ResourceManager.GetString("ExportFileFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Họ và tên không được để trống.
        /// </summary>
        public static string FullNameRequired {
            get {
                return ResourceManager.GetString("FullNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giới tính không hợp lệ.
        /// </summary>
        public static string GenderInvalid {
            get {
                return ResourceManager.GetString("GenderInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập khẩu không thành công..
        /// </summary>
        public static string ImportFileFail {
            get {
                return ResourceManager.GetString("ImportFileFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin trang không hợp lệ.
        /// </summary>
        public static string PageError {
            get {
                return ResourceManager.GetString("PageError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số điện thoại không đúng định dạng.
        /// </summary>
        public static string PhoneNumberInvalid {
            get {
                return ResourceManager.GetString("PhoneNumberInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chức danh không tồn tại.
        /// </summary>
        public static string PositionDoesNotExist {
            get {
                return ResourceManager.GetString("PositionDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên chức danh đã tồn tại.
        /// </summary>
        public static string PositionNameIsDuplicated {
            get {
                return ResourceManager.GetString("PositionNameIsDuplicated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đối tượng không tồn tại, vui lòng tải lại dữ liệu để được cập nhật.
        /// </summary>
        public static string RecordsDoesNotExist {
            get {
                return ResourceManager.GetString("RecordsDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi server, vui lòng liên hệ quản trị viên để được hỗ trợ..
        /// </summary>
        public static string ServerError {
            get {
                return ResourceManager.GetString("ServerError", resourceCulture);
            }
        }
    }
}
